# Should we allow player to duel with their own item?
Duel with own items: true

# SQLite or MySQL storage for win/lose duel.
MySQL:
  # Set to 'true' to use MySQL instead of SQLite for data storage.
  Enabled: false
  Hostname: localhost
  Port: 3306
  Database: your-database
  Username: user
  Password: pass