name: Duel
version: ${project.version}
main: me.zachary.duel.Duel
api-version: 1.13
softdepend: [ CrackShot, Vault, PlaceholderAPI ]
authors: [ Zach_FR ]
description: Duel your friends with this plugin
