name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Maven Cache
      uses: skjolber/maven-cache-github-action@v1.1
      with:
        step: restore

    - name: Build with Maven
      run: mvn package

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        path: target/*.jar

    - name: Maven Cache
      uses: skjolber/maven-cache-github-action@v1.1
      with:
        step: save
